version: '3.4'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo  # Ensures MongoDB starts before API
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: example
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: db1

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
